# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>

sudo: required
dist: xenial
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    packages:
    - libpcap-dev
    - binutils
    - libc-bin

matrix:
    # musl static cross build
    - os: linux
      env:
      - CPPFLAGS="-Ikernel-headers/x86/include/"
      - CFLAGS="-static -m64 -flto -O2"
      - LDFLAGS="-Wl,-m -Wl,elf_x86_64"
      addons:
        apt:
          packages:
          - git
          - musl-tools
      before_script:
      - git clone https://github.com/sabotage-linux/kernel-headers -b v3.12.6-5 kernel-headers
      script:
      - make clean V=s && make V=s CC=musl-gcc && mv ap51-flash ap51-flash-x86_64-linux
    # osx native build
    - os: osx
      before_script:
      - dd if=/dev/urandom of=test.img count=10000 bs=1024
      script:
      - make clean V=s && make V=s ap51-flash-osx
      - make clean V=s && CPPFLAGS="-DDEBUG" make V=s ap51-flash-osx
      - make clean V=s && make V=s EMBED_CI="test.img" ap51-flash-osx
      - make clean V=s && CFLAGS="-flto -O2" make V=s ap51-flash-osx
