# SPDX-FileCopyrightText: Sven Eckelmann <sven@narfation.org>
#
# SPDX-License-Identifier: CC0-1.0

name: Build MacOS

on: [push, pull_request]

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: |
          dd if=/dev/urandom of=test.img count=10000 bs=1024
          make clean V=s && make V=s ap51-flash-osx
          make clean V=s && CPPFLAGS="-DDEBUG" make V=s ap51-flash-osx
          make clean V=s && make V=s EMBED_CI="test.img" ap51-flash-osx
          make clean V=s && CFLAGS="-flto -O2" make V=s ap51-flash-osx
